export const DemandePaiement = {
  table: "DemandePaiement",
  columns: [
    "id_DemandePaiement",           
    "idClient",
    "idTiersFacturation", 
    "dateFacture",
    "idClient_numFactureTiers",
    "dateDebutEmploi",
    "dateFinEmploi",
    "mntAcompte",
    "dateVersementAcompte",
    "mntFactureTTC",
    "mntFactureHT",
    "statut",
    "statutlibelle",
    "inforejet",
    "inforejetcommentaire",
    "mntVirement",
    "dateVirement",
    "ID_Utilisateurs",
    "dateHeureCreation",
    "dateHeureModification",
    "ID_Particulier"
  ],
  defaults: {
    idTiersFacturation: null,
    idClient_numFactureTiers: null,
    dateDebutEmploi: null,
    dateFinEmploi: null,
    mntAcompte: null,
    dateVersementAcompte: null,
    mntFactureTTC: null,
    mntFactureHT: null,
    statut: null,
    statutlibelle: null,
    inforejet: null,
    inforejetcommentaire: null,
    mntVirement: null,
    dateVirement: null,
    ID_Utilisateurs: null,
    dateHeureModification: null,
    ID_Particulier: null
  }
};
