export const EModeOuverture = Object.freeze({
  E_INSCRIPTION_PARTICULIER: "INSCRIPTION_PARTICULIER",
  E_ENVOI_DEMANDE_PAIEMENT: "ENVOI_DEMANDE_PAIEMENT",
  E_ENVOI_DEMANDE_PAIEMENT_MANUEL: "ENVOI_DEMANDE_PAIEMENT_MANUEL",
  E_MIGRATION_ANCIENNES_FACTURES: "MIGRATION_ANCIENNES_FACTURES",
  E_INTEROGATION_PAIEMENT: "INTEROGATION_PAIEMENT",
  E_PARAMETRE_API: "PARAMETRE_API",
  E_NOUVEAU: "NOUVEAU",
  E_MODIFIER: "MODIFIER",
  E_RECHERCHE: "RECHERCHE"
});
